### ISSUE TITLE
How to install additional packages

### ISSUE THREAD

**Issue by page1** [rstudio/cloudml#25]
Just gave it a go. Google munched on the job for 20 minutes just installing the packages, and then finally gave my code a run to find it had not installed `data.table`

Questions:
1. Will the startup process be faster in the future? Are package installations cached or anything?
2. How do I instruct the build to also install my packages?

Does my code need calls to `install.packages`? I will do this, but wondering if there is a better way.

**Comment by page1** [comment]
Hot fix adding the packman package to my code got me going in terms of R packages
```
if (!require("pacman")) install.packages("pacman")
pacman::p_load(keras, 
               cloudml, 
               readr,
               data.table,
               dplyr)
```

**Comment by javierluraschi** [comment]
1. Startup time is much faster since a cache has been implemented, first run is still bit slow, but subsequent ones are much faster.
2. `cloudml` now uses packrat which will detect additional packages you are using and make sure the same versions are deployed in cloudml, packrat is enabled by default so this should just work.
