### ISSUE TITLE
error: cloudml package not available

### ISSUE THREAD

**Issue by jjallaire** [rstudio/cloudml#66]
Just executed a training job to test the new `cloudml::is_cloudml()` function and got this error:

<img width="861" alt="screen shot 2017-12-12 at 11 01 29 am" src="https://user-images.githubusercontent.com/104391/33894437-01a21444-df2c-11e7-943e-d60e66190c53.png">

Is the cloudml package available during training? (seems like it should be)

**Comment by jjallaire** [comment]
Also occurs for `library(cloudml)`

<img width="860" alt="screen shot 2017-12-12 at 11 08 49 am" src="https://user-images.githubusercontent.com/104391/33894812-e77f0be8-df2c-11e7-83cf-d07fa394d86d.png">

**Comment by javierluraschi** [comment]
It's a bit tricky to load `cloudml` in packrat during development; therefore, this line was added:

https://github.com/rstudio/cloudml/blob/master/R/scope.R#L17-L32

This can be commented and we would get cloudml during training, but then it adds the problem of how to update cloudml while being developed since all changes would have to be pushed to github during each training run for packrat to be able to restore them from cloudml.

So far, I've rather assumed that cloudml is not available during training but we can switch to use cloudml from github if needed.

**Comment by jjallaire** [comment]
We will definitely need it turning training as functions like gcloud_copy, gcloud_sync, and gcloud_bucket will be needed within training scripts. Could we do something like use the cloudml development version if the run is being initiated from within the dev directory of cloudml and use the github version otherwise? (note that ultimately we will need to use the version of cloudml in use on the client workstation)

**Comment by javierluraschi** [comment]
Just pushed a commit to removed from ignored packages and trained a couple times even with cloudml changes, seems to work just fine but I'll keep an eye in case we are missing something.
